const dumy = [
    {
      id: 1,
      type: "tips",
      date: "2021. 01. 01",
      topic: "은행업무Tip",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 2,
      type: "report",
      date: "2021. 01. 01",
      topic: "IBK연구보고서",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 3,
      type: "economic",
      date: "2021. 01. 01",
      topic: "경제/금융정보",
      title: "은행업무Tip", 
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 4,
      type: "magazin",
      date: "2021. 01. 01",
      topic: "매거진",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 5,
      type: "financialMarket",
      date: "2021. 01. 01",
      topic: "금융시장동향",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 6,
      type: "consulting",
      date: "2021. 01. 01",
      topic: "컨설팅보고서/전문가컬럼",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 7,
      type: "property",
      date: "2021. 01. 01",
      topic: "매각부동산",
      title: "은행업무Tip",
      tags: ["일중시황" ],
    },
    {
      id: 1,
      type: "tips",
      date: "2021. 01. 01",
      topic: "은행업무Tip",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 2,
      type: "report",
      date: "2021. 01. 01",
      topic: "IBK연구보고서",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 3,
      type: "economic",
      date: "2021. 01. 01",
      topic: "경제/금융정보",
      title: "은행업무Tip", 
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 4,
      type: "magazin",
      date: "2021. 01. 01",
      topic: "매거진",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 5,
      type: "financialMarket",
      date: "2021. 01. 01",
      topic: "금융시장동향",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 6,
      type: "consulting",
      date: "2021. 01. 01",
      topic: "컨설팅보고서/전문가컬럼",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 7,
      type: "property",
      date: "2021. 01. 01",
      topic: "매각부동산",
      title: "은행업무Tip",
      tags: ["일중시황" ],
    },
    {
      id: 1,
      type: "tips",
      date: "2021. 01. 01",
      topic: "은행업무Tip",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 2,
      type: "report",
      date: "2021. 01. 01",
      topic: "IBK연구보고서",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 3,
      type: "economic",
      date: "2021. 01. 01",
      topic: "경제/금융정보",
      title: "은행업무Tip", 
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 4,
      type: "magazin",
      date: "2021. 01. 01",
      topic: "매거진",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 5,
      type: "financialMarket",
      date: "2021. 01. 01",
      topic: "금융시장동향",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 6,
      type: "consulting",
      date: "2021. 01. 01",
      topic: "컨설팅보고서/전문가컬럼",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 7,
      type: "property",
      date: "2021. 01. 01",
      topic: "매각부동산",
      title: "은행업무Tip",
      tags: ["일중시황" ],
    },
    {
      id: 1,
      type: "tips",
      date: "2021. 01. 01",
      topic: "은행업무Tip",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 2,
      type: "report",
      date: "2021. 01. 01",
      topic: "IBK연구보고서",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 3,
      type: "economic",
      date: "2021. 01. 01",
      topic: "경제/금융정보",
      title: "은행업무Tip", 
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 4,
      type: "magazin",
      date: "2021. 01. 01",
      topic: "매거진",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 5,
      type: "financialMarket",
      date: "2021. 01. 01",
      topic: "금융시장동향",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 6,
      type: "consulting",
      date: "2021. 01. 01",
      topic: "컨설팅보고서/전문가컬럼",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 7,
      type: "property",
      date: "2021. 01. 01",
      topic: "매각부동산",
      title: "은행업무Tip",
      tags: ["일중시황" ],
    },
    {
      id: 1,
      type: "tips",
      date: "2021. 01. 01",
      topic: "은행업무Tip",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 2,
      type: "report",
      date: "2021. 01. 01",
      topic: "IBK연구보고서",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 3,
      type: "economic",
      date: "2021. 01. 01",
      topic: "경제/금융정보",
      title: "은행업무Tip", 
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 4,
      type: "magazin",
      date: "2021. 01. 01",
      topic: "매거진",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 5,
      type: "financialMarket",
      date: "2021. 01. 01",
      topic: "금융시장동향",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 6,
      type: "consulting",
      date: "2021. 01. 01",
      topic: "컨설팅보고서/전문가컬럼",
      title: "은행업무Tip",
      tags: ["일중시황", "일중시황", "일중시황", "일중시황"],
    },
    {
      id: 7,
      type: "property",
      date: "2021. 01. 01",
      topic: "매각부동산",
      title: "은행업무Tip",
      tags: ["일중시황" ],
    },
    
  ];

  export default dumy