const dumy = [
    {
      id: 1,
      title: "자금운용부의모닝커피와마켓(20210817)_미국테이퍼링은 언제부터?",
      description: "가상자산 거래소 빗썸은 우수 소프트웨어(SW)개발자 양성 프로그램'빗썸테크아카데미'를 본격적으로 시작한다고 18일 밝혔다.",
      location : '본사',
      userName : '박종옥사원',
      reference: '아이뉴스 24',
      portal: "네이버",
      date: "2021. 01. 01",
      comment: "",
      type: "scrap",
    },
    {
      id: 2,
      title: "포트폴리오_김병수_2.pdf",
      description: "포트폴리오 김병수 자료입니다.",
      location : '본사',
      userName : '박종옥사원',
      reference: 'PDF 자료',
      portal: "",
      date: "2021. 01. 01",
      comment: "",
      type: "pdf",
    },
    {
      id: 3,
      title: "자금운용부의모닝커피와마켓(20210817)_미국테이퍼링은 언제부터?",
      description: "가상자산 거래소 빗썸은 우수 소프트웨어(SW)개발자 양성 프로그램'빗썸테크아카데미'를 본격적으로 시작한다고 18일 밝혔다.",
      location : '본사',
      userName : '박종옥사원',
      reference: '아이뉴스 24',
      portal: "네이버",
      date: "2021. 01. 01",
      comment: "가상자산거래소 빗썸 우수 소프트웨어 개발자 양성프로그램 자료",
      type: "scrap",
    },
    {
      id: 4,
      title: "포트폴리오_김병수_2.pdf",
      description: "포트폴리오 김병수 자료입니다.",
      location : '본사',
      userName : '박종옥사원',
      reference: 'PDF 자료',
      portal: "",
      date: "2021. 01. 01",
      comment: "",
      type: "pdf",
    },
  
  ];
  export default dumy